### ISSUE TITLE
Add communication channel in readme file

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/BudgetApp#10]
Members should interact with each other so there should be the channel
slack link https://join.slack.com/t/newworkspace-uco4265/shared_invite/zt-huokfrna-unLOpo_bo7fKACHZ2rH7jA
WhatsApp link https://chat.whatsapp.com/DgTQGaEXclZLKu6xhoFhjp

**Comment by sainitishkumar** [comment]
Hi can you check PR #11

**Comment by gouri-panda** [comment]
@sainitishkumar Could you also add the WhatsApp link.

**Comment by sainitishkumar** [comment]
I have updated it
