### ISSUE TITLE
Add dark theme in app

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/BudgetApp#12]
Right now we have only a light theme. In order to. improve the user experience we should add both a dark theme and a light theme.
* Expected behavior
Users can select both a light theme or dark theme by a toggle switch

**Comment by bislara** [comment]
Hey, I want to work on this issue. Can you assign it to me?

**Comment by NirajSrivastava18** [comment]
Hey, Can I work on this please? If yes, assign it to me

**Comment by gouri-panda** [comment]
@bislara  please go-ahead.

**Comment by Michaela115** [comment]
Je možné na tom pracovať?

**Comment by gouri-panda** [comment]
@Michaela115 This issue has solved.
