### ISSUE TITLE
Remove Negative sign from total amount

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/BudgetApp#2]
* Describe the bug
A Negative sign is showing the total amount.
* Expected behavior
There should be no negative sign(-) in the total amount.

**Comment by iamrajatg** [comment]
May i work on this :) ?

**Comment by gouri-panda** [comment]
sure @iamrajatg go ahead!

**Comment by BhuvaneshPatil** [comment]
> * Describe the bug
>   A Negative sign is showing the total amount.
> * Expected behavior
>   There should be no negative sign(-) in the total amount.

where ??
below the line "Available Budget in.."..?

**Comment by gouri-panda** [comment]
<img width="1299" alt="Screenshot 2020-10-04 at 8 40 22 PM" src="https://user-images.githubusercontent.com/43576162/95019245-d50ed900-0681-11eb-83f7-38e837de9a89.png">

> below the line "Available Budget in.."..?

yes

**Comment by BhuvaneshPatil** [comment]
> <img alt="Screenshot 2020-10-04 at 8 40 22 PM" width="1299" src="https://user-images.githubusercontent.com/43576162/95019245-d50ed900-0681-11eb-83f7-38e837de9a89.png">
> 
> @BhuvaneshPatil here

ok so initially there should only "0.00" ?

**Comment by gouri-panda** [comment]
yes @BhuvaneshPatil
