### ISSUE TITLE
Expanse title is a little weird

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/BudgetApp#51]
<img width="1400" alt="Screenshot 2020-10-08 at 2 56 58 AM" src="https://user-images.githubusercontent.com/43576162/95389769-eff77c80-0911-11eb-8239-bec65ceaaa52.png">

*Expected Behaviour 
Expanse title should be horizontally same with the Income title

**Comment by erdemuslu** [comment]
I'm working on it. Can you assign me? @gouri-panda

**Comment by erdemuslu** [comment]
I fixed it now. @gouri-panda 
PR: #52
