### ISSUE TITLE
Missing Alert field in save button if users forgot a field

### ISSUE THREAD

**Issue by gouri-panda** [gouri-panda/BudgetApp#7]
* Describe the bug
Right now if we save the income/outcome without the currency there is nothing shows up.
* Expected behavior
There should be an alert in which the field is missing.

**Comment by JoaoVSouto** [comment]
Hey! I can take this one :smile:

**Comment by gouri-panda** [comment]
@JoaoVSouto yes go ahead!

**Comment by deepharshsri** [comment]
Hi there! Can I work on this?
